#+STARTUP: showall
#+OPTIONS: toc:nil num:nil
#+BEGIN_EXPORT html
---
layout: default
title: About
---
#+END_EXPORT

#+TOC: headlines

* About Me
Hi, my name is Matthew Rothlisberger. I am an aspiring electrical
engineer and software developer.

I am passionate about engineering as a mechanism to improve our world;
I find it fulfilling to implement effective solutions for difficult
and meaningful problems. Whenever possible, I try to discover, learn,
and use the best tools available. My [[file:projects.org][projects]] showcase some of my
work.

* About This Site
This site serves as a portfolio of my education, my work experience,
and of the engineering projects I have taken on over the
years. Sufficiently notable projects will be added and updated as I
make progress.

My [[file:blog.org][blog]] is also hosted here. It is a place for me to write about
problems and solutions that interest me, primarily in the fields of
electrical engineering and software engineering. New posts will arrive
when I write them.

For more information on the technologies used to build this site,
consult the [[file:colophon.org][colophon]].

* Education
To date, most recent to least recent:

** Utah State University
/2021 - 2025/

*Admitted*

*B.S. Electrical Engineering*

I have been admitted to Utah State University for a bachelor of
science degree in electrical engineering. Because of the ongoing
pandemic, I chose to defer my admission and will be starting classes
around early 2021.

** Thomas Jefferson High School for Science and Technology
/2016 - 2020/

*Graduated*

*Electrical Engineering Focus*

I attended TJHSST for ninth through twelfth grades after being
admitted through an extensive application process. The highlights of
my experience were the two years of hands on electrical engineering
classes I took. We began with analog circuit design and built up to
processor design, signal processing, and more.

* Work Experience
Again, most to least recent:

** Junior Software Developer
/2020 -/

*Freelance*

I am freelancing while seeking full time remote employment. During
this time, I am working on a variety of software projects using
languages and tools I am familiar with. Whenever I have time, I work
on open source and make an effort to learn valuable new engineering
skills.

** Senior Audiovisual Technician
/2018 - 2020/

*Fairfax County Public Schools*

I was responsible for overseeing dozens of community events in an
auditorium that seats several hundred people. I developed proficiency
hanging and programming lighting fixtures; interfacing audio equipment
and equalizing signals; and working with customers of many cultures to
see their events through. I often worked under time pressure and under
unforeseen circumstances to ensure that events ran well.
