#+STARTUP: showall
#+OPTIONS: toc:nil num:nil
#+BEGIN_EXPORT html
---
layout: default
title: Projects
---
#+END_EXPORT

This is a list of my personal projects. Many are engineering efforts
and some were undertaken for the sake of learning. I feel that all
those listed are notable enough to include for now, but some will be
removed in the future, and more will certainly be added.

Several of these projects are not yet completed to my satisfaction,
and I am continuing work on the ones that I consider most valuable.

* [[https://github.com/asterane/asterane.github.io][This Website]]
A personal homepage, blog, and portfolio website. Written from scratch
to be fast, clean, and responsive. Also see the colophon.

* [[https://github.com/asterane/processor-design][Processor Design]]
Designing a custom sixteen bit central processing unit, and
constructing it out of discrete logic components.

* [[https://github.com/asterane/the-grid][The Grid]]
[Readme forthcoming] Design through full implementation of a
completely custom LED display wall and software to control it,
measuring 12 feet high by 20 feet wide.

* [[https://github.com/asterane/analog-design][Analog Circuit Design]]
Construction of a high fidelity 90 watt audio power amplifier. Also, a
voltage controlled oscillator design for frequency modulation.

* Real Time Digital Signal Processing
[Repository forthcoming] Creating algorithms to correct audio
distortion from speakers and the environment. Written for processors
and FPGA.

* Raycasting Demonstration
[Repository forthcoming] Project to create a first person 3D game in
the style of Doom, using Java. Can move around single layer 3D
environment.

* Set Design
[Repository forthcoming] Design and construction of all sets for
several large theatrical shows. Used computer aided design.

* Robot Design
[Repository forthcoming] Building the chassis for a custom wheeled
robot using cheap materials, and writing software for it.

* Emacs Configuration
[Repository forthcoming] My personal Emacs configuration file, with
all the customization I use to do my work from day to day.

* C Exercises
[Repository forthcoming] Practice programming using the low level C
language, dealing with memory management, and creating efficient
code.

* Rust Exercises
[Repository forthcoming] Learning the relatively new Rust systems
language and its many features characteristic of higher level
languages.

* Python Exercises
[Repository forthcoming] Early work learning how to program computers,
as well as later efforts in scripting various tasks.

